import 'package:flutter/material.dart';


const textTheme = TextTheme(
  displayLarge: TextStyle(
    fontFamily: "Zarids",
    fontSize: 35,
  ),
  displayMedium: TextStyle(
    fontFamily: "Zarids",
    fontSize: 30,
  ),
  displaySmall: TextStyle(
    fontFamily: "Zarids",
    fontSize: 25,
  ),
  headlineMedium: TextStyle(
    fontFamily: "Zarids",
    fontSize: 20,
  ),
  headlineSmall: TextStyle(
    fontFamily: "Zarids",
    fontSize: 15,
  ),
  titleLarge: TextStyle(
    fontFamily: "Zarids",
    fontSize: 20,
  ),
);

const lightColorScheme = ColorScheme(
  brightness: Brightness.light,
  primary: Color(0xFF006A6A),
  onPrimary: Color(0xFFFFFFFF),
  primaryContainer: Color(0xFF6FF7F6),
  onPrimaryContainer: Color(0xFF002020),
  secondary: Color(0xFF785A00),
  onSecondary: Color(0xFFFFFFFF),
  secondaryContainer: Color(0xFFFFDF9B),
  onSecondaryContainer: Color(0xFF251A00),
  tertiary: Color(0xFF006493),
  onTertiary: Color(0xFFFFFFFF),
  tertiaryContainer: Color(0xFFCAE6FF),
  onTertiaryContainer: Color(0xFF001E30),
  error: Color(0xFFBA1A1A),
  errorContainer: Color(0xFFFFDAD6),
  onError: Color(0xFFFFFFFF),
  onErrorContainer: Color(0xFF410002),
  surface: Color(0xFFFAFDFC),
  onSurface: Color(0xFF191C1C),
  surfaceContainerHighest: Color(0xFFDAE5E4),
  onSurfaceVariant: Color(0xFF3F4948),
  outline: Color(0xFF6F7979),
  onInverseSurface: Color(0xFFEFF1F0),
  inverseSurface: Color(0xFF2D3131),
  inversePrimary: Color(0xFF4CDADA),
  shadow: Color(0xFF000000),
  surfaceTint: Color(0xFF006A6A),
  outlineVariant: Color(0xFFBEC9C8),
  scrim: Color(0xFF000000),
);

const darkColorScheme = ColorScheme(
  brightness: Brightness.dark,
  primary: Color(0xFF4CDADA),
  onPrimary: Color(0xFF003737),
  primaryContainer: Color(0xFF004F50),
  onPrimaryContainer: Color(0xFF6FF7F6),
  secondary: Color(0xFFF1C048),
  onSecondary: Color(0xFF3F2E00),
  secondaryContainer: Color(0xFF5B4300),
  onSecondaryContainer: Color(0xFFFFDF9B),
  tertiary: Color(0xFF8DCDFF),
  onTertiary: Color(0xFF00344F),
  tertiaryContainer: Color(0xFF004B70),
  onTertiaryContainer: Color(0xFFCAE6FF),
  error: Color(0xFFFFB4AB),
  errorContainer: Color(0xFF93000A),
  onError: Color(0xFF690005),
  onErrorContainer: Color(0xFFFFDAD6),
  surface: Color(0xFF191C1C),
  onSurface: Color(0xFFE0E3E2),
  surfaceContainerHighest: Color(0xFF3F4948),
  onSurfaceVariant: Color(0xFFBEC9C8),
  outline: Color(0xFF889392),
  onInverseSurface: Color(0xFF191C1C),
  inverseSurface: Color(0xFFE0E3E2),
  inversePrimary: Color(0xFF006A6A),
  shadow: Color(0xFF000000),
  surfaceTint: Color(0xFF4CDADA),
  outlineVariant: Color(0xFF3F4948),
  scrim: Color(0xFF000000),
);
